version: "2"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:80"
    volumes:
     - .:/var/www
#  https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: es
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
      - "network.host=0.0.0.0"
    ports:
      - "9200:9200"
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data